dist: trusty
language: cpp
matrix:
  fast_finish: true
  include:
  - compiler: gcc
    env: OS=linux COMPILER=gcc-6 UBUNTU=17.04
    install:
    - travis/travis_ci_install_linux.sh
    os: linux
    script:
    - cd ${TRAVIS_BUILD_DIR}/ && travis/postsubmit.sh cppunit "." Debug
    - cd ${TRAVIS_BUILD_DIR}/ && travis/postsubmit.sh cppunit "." Release
    - sudo chown -R $USER:$USER *
    after_success:
    - cd ${TRAVIS_BUILD_DIR}/build/install && tar cfzv ../cppunit_${OS}_${COMPILER}.tar
      *
  - compiler: clang
    env: OS=linux COMPILER=clang-4.0 UBUNTU=17.04
    install:
    - travis/travis_ci_install_linux.sh
    os: linux
    script:
    - cd ${TRAVIS_BUILD_DIR}/ && travis/postsubmit.sh cppunit "." Debug
    - cd ${TRAVIS_BUILD_DIR}/ && travis/postsubmit.sh cppunit "." Release
    - sudo chown -R $USER:$USER *
    after_success:
    - cd ${TRAVIS_BUILD_DIR}/build/install && tar cfzv ../cppunit_${OS}_${COMPILER}.tar
      *
  - compiler: gcc
    env: COMPILER=gcc-6 OS=osx
    os: osx
    osx_image: xcode8
    install:
    - travis/travis_ci_install_osx.sh
    script:
    - cd ${TRAVIS_BUILD_DIR}/ && travis/postsubmit.sh cppunit "." Debug
    - cd ${TRAVIS_BUILD_DIR}/ && travis/postsubmit.sh cppunit "." Release
    after_success:
    - cd ${TRAVIS_BUILD_DIR}/build/install && tar cfzv ../cppunit_${OS}_${COMPILER}.tar
      *
  - compiler: clang
    env: COMPILER=clang-4.0 STL=libc++ OS=osx
    os: osx
    osx_image: xcode8
    install:
    - travis/travis_ci_install_osx.sh
    script:
    - cd ${TRAVIS_BUILD_DIR}/ && travis/postsubmit.sh cppunit "." Debug
    - cd ${TRAVIS_BUILD_DIR}/ && travis/postsubmit.sh cppunit "." Release
    after_success:
    - cd ${TRAVIS_BUILD_DIR}/build/install && tar cfzv ../cppunit_${OS}_${COMPILER}.tar
      *
  - compiler: clang
    env: COMPILER=clang-default STL=libc++ OS=osx
    os: osx
    osx_image: xcode8
    install:
    - travis/travis_ci_install_osx.sh
    script:
    - cd ${TRAVIS_BUILD_DIR}/ && travis/postsubmit.sh cppunit "." Debug
    - cd ${TRAVIS_BUILD_DIR}/ && travis/postsubmit.sh cppunit "." Release
    after_success:
    - cd ${TRAVIS_BUILD_DIR}/build/install && tar cfzv ../cppunit_${OS}_xcode8.tar
      *
services:
- docker
sudo: required

deploy:
  provider: releases
  api_key:
    secure: O4cJk4Y4qx8SDO3NOa9HR0V0MrYyHHkTMRrIHPXR55W496du+rBmQnMaDpzBDbtz0J2It+p4UJEvyI4QDYShHZrNZP7Y4+CU2Tv9IBeX4HRz5xBuLlIIYicW5j6tvQOb7UOMposzikxGeEodr5KrOA7e0OKiYDc6A+iuVXnUv/Cn99BuUqtIDMfBwn/4RTD8E2KfUcrjeEspXnqVJYSa20HA4IA83TaL5HiNsPBNXgHgLWDLVpYGoEPUu90e9P9ENN66FOHf2k16kEtdd6cWUprZUthfx5dfs4lAP49WuI/XRrjrKAY94vBu1RRwS2XeSeKr/d0+9ZFHhGS4RsdOBukTuEr0w3YihhR3/Vqq9+ErfZKTAx/PLKVp4I0Knwmr707OJKdfnOrOQ8MC1R/ifvhuaHXTNJzKaD4dgwulKLxyxv6vQAJNu7kZ+wXR8AJav48UpYsypMrWAUmpInu7cStYMmWhtkZTbGko6+RYhZYI7ekuEPuNfyL2B3XhGKb2qS89TkBcm9YpS1kNc8Q3Wdjw+/FsIHRLUivZiBRJly8Sn4ulFx2Vh/mZN97W4x2v9Rn+m+yXJ+SImM7MT01mldzj5XdDGHBkBrxsHut7WpP6whceKOUoKDARW5J5CRjcovZOtNX2E8isssH67HqEkdDFPgXLgFfn8/XBl4/u8dc=
  file_glob: true
  file: ${TRAVIS_BUILD_DIR}/build/cppunit_*.tar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true